### ISSUE TITLE
结构试验室 摇窗机本地log文件无法及时更新

### ISSUE THREAD

**Issue by woshishanji** [maboss-YCMan/work_issue#18]

**Comment by woshishanji** [comment]
本地log文件更新到4月20号，influxdb中也更新到了4月20号；问题可能与设备厂商程序有关

**Comment by bty2000** [comment]
2#摇窗机：设备log正常更新，采集log日志路径有误，需要更改路径；
1#摇窗机：路径正确，网络通，但仍没有数据上传；

**Comment by Fatekiller23** [comment]
got

**Comment by Fatekiller23** [comment]
2#设备路径已经更改，正常传数。
1#更改状态变量笔误，目前正常
