### ISSUE TITLE
"标准调温调湿试验箱(一)"没有数据上传

### ISSUE THREAD

**Issue by bty2000** [maboss-YCMan/work_issue#2]
- "标准调温调湿试验箱(一)"没有数据上传

**Comment by Fatekiller23** [comment]
重新注册了服务，目前良好

**Comment by Fatekiller23** [comment]
又发生同样问题。

**Comment by HeathKang** [comment]
可以看下log

**Comment by Fatekiller23** [comment]
暂时解决办法 用crontab 定时任务 每小时启动一次

需要在本地拿黑盒子实测。如果实测不能发现错误的话，将：
放弃多线程， 用两个进程分别注册两个服务获取两台设备的数据
