### ISSUE TITLE
TTS 跟踪

### ISSUE THREAD

**Issue by Fatekiller23** [maboss-YCMan/work_issue#20]
level 改成 tag

**Comment by Fatekiller23** [comment]
时间 有两种 一种从日志内容取

一种是日志中没有的，直接附上现有时间

**Comment by Fatekiller23** [comment]
需要判定 机器上自带的log里面的时间是不是正确的。
现在情况是有一台正确，有一天不正确，其他未知

**Comment by bty2000** [comment]
TTS通过抓“history”窗口、“*.NC”窗口采集数据，但设备非常规关机后软件重启报错，需重新恢复软件方可使用，原因待查。

**Comment by bty2000** [comment]
5#TTS时间超前
