### ISSUE TITLE
MTS_Damper 没有数据上传

### ISSUE THREAD

**Issue by bty2000** [maboss-YCMan/work_issue#24]

**Comment by Fatekiller23** [comment]
damer设备里的日志是实时更新写入到文件的，但是因为软件内部包含的时间是2005年，所以watchman得最新数据全部上传到2005年区间，导致看起来没有最新数据上传

**Comment by bty2000** [comment]
设备电脑主板电池亏电，导致开机后时间出错，需手动调整时间。
