### ISSUE TITLE
NVH 四转股没有数据上传

### ISSUE THREAD

**Issue by bty2000** [maboss-YCMan/work_issue#29]
数据更新到4月26日

**Comment by Fatekiller23** [comment]
日志表明ziyan仍在运行，初步判断还是连接redis时，实例僵死的问题
解决办法正在考虑

**Comment by Fatekiller23** [comment]
4月26日 NVH转股报错，更新了系统，但是软件没有开AK协议，程序不能上传数据
等待转股供应商来保养设备，fix
