### ISSUE TITLE
MTS 柔性液压系统

### ISSUE THREAD

**Issue by bty2000** [maboss-YCMan/work_issue#31]
1、日志信息停止更新到5月5日早上
2、进度信息停止更新到4月24日

**Comment by Fatekiller23** [comment]
因为 这两台都是由redis入队的，所以很有可能是因为 跟CWT一样的chitu线程僵死问题。
解决办法：撸一个新的chitu

**Comment by Fatekiller23** [comment]
程序内部写日志时间少一天，暂时无解决办法

进度信息暂时使用重启赤兔脚本解决
